language: node_js
node_js:
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
branches:
  only:
    - master
    - develop
    - release
install:
  - npm install
before_script:
  - npm run lint
  - npm run lint:test
  - npm test
script:
  - npm run build
after_success:
  - npm run test:coveralls
